plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
include:
  - Programming.md
  - tools.md
  - bash.md
  - git.md
  - vim.md
  - tmux.md
  - xdebug.md
  - sql.md
  - curl.md
  - Others.md
  - php.md
  - PhpConference2019.md
